# Tokyo Night theme for i3status-rust

theme = "plain"
icons = "awesome6"

[theme.overrides]
idle_bg = "#1a1b26"
idle_fg = "#a9b1d6"
info_bg = "#7aa2f7"
info_fg = "#1a1b26"
good_bg = "#9ece6a"
good_fg = "#1a1b26"
warning_bg = "#e0af68"
warning_fg = "#1a1b26"
critical_bg = "#f7768e"
critical_fg = "#1a1b26"
separator = "#32344a"
separator_bg = "#1a1b26"
separator_fg = "#32344a"

[[block]]
block = "focused_window"
max_width = 50
show_marks = "visible"

[[block]]
block = "workspaces"
icons_format = "{icon}"

[[block]]
block = "music"
player = "spotify"
max_width = 20
hide_when_empty = true
separator = " | "

[block.click]
button = "left"
cmd = "playerctl play-pause"

[[block]]
block = "cpu"
interval = 1
format = " $icon $utilization "

[[block]]
block = "memory"
format = " $icon $mem_used_percents "

[[block]]
block = "disk_space"
path = "/"
info_type = "available"
alert_unit = "GB"
alert = 10.0
warning = 15.0
format = " $icon $available "

[[block]]
block = "net"
device = "auto"
format = " $icon $speed_down.eng(prefix:K) / $speed_up.eng(prefix:K) "
inactive_format = " $icon × "

[[block]]
block = "sound"
driver = "pulseaudio"
format = " $icon $volume "
headphones_indicator = true

[block.click]
button = "left"
cmd = "pavucontrol"

[[block]]
block = "battery"
interval = 10
format = " $icon $percentage "

[[block]]
block = "time"
interval = 60
format = " $icon $timestamp.datetime(f:'%a %d/%m %R') "