#!/bin/sh

# Omarchy-X .xinitrc - X11 session startup script

# Set environment variables
export XDG_CURRENT_DESKTOP=i3
export XDG_SESSION_DESKTOP=i3
export XDG_SESSION_TYPE=x11

# Start i3 window manager
exec i3