# Everforest theme for i3status-rust

icons = "awesome6"

[theme]
name = "plain"

[theme.overrides]
idle_bg = "#2d353b"
idle_fg = "#d3c6aa"
info_bg = "#7fbbb3"
info_fg = "#2d353b"
good_bg = "#a7c080"
good_fg = "#2d353b"
warning_bg = "#dbbc7f"
warning_fg = "#2d353b"
critical_bg = "#e67e80"
critical_fg = "#2d353b"
separator = "#475258"
separator_bg = "#2d353b"
separator_fg = "#475258"

[[block]]
block = "focused_window"
max_width = 50

[[block]]
block = "music"
player = "spotify"
max_width = 20
hide_when_empty = true
separator = " | "

[block.click]
button = "left"
cmd = "playerctl play-pause"

[[block]]
block = "cpu"
interval = 1
format = " $icon $utilization "

[[block]]
block = "memory"
format = " $icon $mem_used_percents "

[[block]]
block = "disk_space"
path = "/"
info_type = "available"
alert_unit = "GB"
alert = 10.0
warning = 15.0
format = " $icon $available "

[[block]]
block = "net"
device = "auto"
format = " $icon $speed_down.eng(prefix:K) / $speed_up.eng(prefix:K) "
inactive_format = " $icon × "

[[block]]
block = "sound"
driver = "pulseaudio"
format = " $icon $volume "
headphones_indicator = true

[block.click]
button = "left"
cmd = "pavucontrol"

[[block]]
block = "battery"
interval = 10
format = " $icon $percentage "

[[block]]
block = "time"
interval = 60
format = " $icon $timestamp.datetime(f:'%a %d/%m %R') "